name: pokeroute
description: A simple optimized route generator for gps locations

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  get_it: ^5.0.1
  http: ^0.12.0+2
  intl: ^0.16.1
  latlong: ^0.6.1
  expandable: ^4.1.4
  md2_tab_indicator: ^1.0.2
  quiver: ">=2.0.0 <3.0.0"
  duration: "<3.0.0"
  gpx: ^1.1.1
  autocomplete_textfield: ^1.7.3
  pokeapi: ^1.0.1
  responsive: 0.2.3+4
  clipboard: ^0.1.2+8

dev_dependencies:
  pedantic: ^1.9.2

dependency_overrides:
  # https://github.com/prathanbomb/pokedart/issues/7
  pokeapi:
    git:
      url: https://github.com/prathanbomb/pokedart
      path: pokeapi

flutter:
  uses-material-design: true

  assets:
    - web/assets/
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.otf

transformers:
  - $dart2js:
      analyzeAll: true
      checked: true
      csp: true
      minify: true
      sourceMaps: false
      suppressHints: false
      suppressWarnings: false
      verbose: true
