name: pokeroutes
description: A simple optimized route generator for gps locations

environment:
    # You must be using Flutter >=1.5.0 or Dart >=2.3.0
    sdk: ">=2.3.0 <3.0.0"

dependencies:
    flutter_web: any
    flutter_web_ui: any
    provider: ^3.0.0+1
    get_it: any
    http: ^0.12.0+2
    intl: any
    latlong: any
    expandable: any
    md2_tab_indicator: ^1.0.2
    quiver: ">=2.0.0 <3.0.0"
    duration: "<3.0.0"
    gpx: ^0.0.1
    autocomplete_textfield: ^1.7.3
    pokeapi: ^1.0.1
    responsive: 0.2.3+4

dev_dependencies:
    build_runner: ^1.5.0
    build_web_compilers: ^2.1.0
    pedantic: ^1.7.0
    test: any

dependency_overrides:
    flutter_web:
        git:
            url: https://github.com/flutter/flutter_web
            path: packages/flutter_web
    flutter_web_ui:
        git:
            url: https://github.com/flutter/flutter_web
            path: packages/flutter_web_ui
    provider:
        git:
            url: https://github.com/kevmoo/provider
            ref: flutter_web
    expandable:
        git:
            url: https://github.com/CiriousJoker/flutter-expandable
    md2_tab_indicator:
        git:
            url: https://github.com/CiriousJoker/md2_tab_indicator
    autocomplete_textfield:
        git:
            url: https://github.com/CiriousJoker/flutter-autocomplete-textfield
    pokeapi:
        git:
            url: https://github.com/CiriousJoker/pokedart
            path: pokeapi
    responsive:
        git:
            url: https://github.com/CiriousJoker/responsive

flutter:
    uses-material-design: true

    assets:
        - web/assets/

transformers:
- $dart2js:
    analyzeAll: true
    checked: true
    csp: true
    minify: true
    sourceMaps: true
    suppressHints: false
    suppressWarnings: false
    verbose: true
